In [96]:
# load defaulft config
import yaml
import os

config_path = './configs/Active_v0.yml'

with open(config_path) as file:
    # The FullLoader parameter handles the conversion from YAML
    # scalar values to Python the dictionary format
    config = yaml.load(file, Loader=yaml.FullLoader)

# create base dir and gr
if os.path.exists(config["PROJECT"]["project_dir"]) is False:
    os.mkdir(config["PROJECT"]["project_dir"])

if os.path.exists(config["PROJECT"]["group_dir"]) is False:
    os.mkdir(config["PROJECT"]["group_dir"])

In [2]:
import pandas as pd
import numpy as np

In [4]:
path_np = os.path.join(config['PROJECT']['group_dir'],'Stage_'+str(0),'evaluation')
path_np

'/mnt/Ressources/Andres/Temp_active/runs/Active_Learning_v0/Stage_0/evaluation'

In [7]:
np_list =[]
for i in range(5):
    np_list.append(np.load(os.path.join(path_np,str(i)+'npy.npy')))

In [67]:
in_max_scaler = preprocessing.MinMaxScaler()

In [103]:
to_compu ={}
to_compu['s_uncertanty'] = min_max_scaler.fit_transform(np_list[2].reshape(-1, 1)).squeeze()
to_compu['uncertanty'] = np_list[2]#.reshape(-1, 1)
to_compu['indexes'] = np_list[4]#.reshape(-1, 1)

In [104]:
df_uncertainty =  pd.DataFrame(to_compu)

In [108]:
df_uncertainty.sort_values('s_uncertanty',ascending=False,inplace=True)

In [127]:
ordered_indexes  =df_uncertainty['indexers'].to_numpy()

In [128]:
ordered_indexes

array([ 1611, 42369, 18636, ..., 36618,   772, 49190])

In [130]:
df_uncertainty.reset_index(drop=True,inplace=True)

s_uncertanty  uncertanty  indexers
0          1.000000    3.541582      1611
1          0.998211    3.504629     42369
2          0.996399    3.467202     18636
3          0.995579    3.450284     30572
4          0.994934    3.436961     17520
5          0.992933    3.395629      2345
6          0.992683    3.390470      5314
7          0.989275    3.320085     30896
8          0.989266    3.319893     11479
9          0.989228    3.319103     38787
10         0.987613    3.285745     25141
11         0.987326    3.279819      7804
12         0.986902    3.271077     44783
13         0.986848    3.269945     25862
14         0.985507    3.242251      8750
15         0.984803    3.227726     43793
16         0.984518    3.221826     21875
17         0.984122    3.213657     23695
18         0.984009    3.211326     12357
19         0.983330    3.197291     43000
20         0.983261    3.195861      3536
21         0.982844    3.187250     21422
22         0.982767    3.185675     36325
23         0.982705    3.184380     43083
24         0.982131    3.172538      9649
25         0.982015    3.170135     48250
26         0.981812    3.165955     43403
27         0.981608    3.161723      2747
28         0.981357    3.156543      4822
29         0.980718    3.143350      6397
...             ...         ...       ...
48970      0.407313   -8.699195      3153
48971      0.406407   -8.717897     35878
48972      0.396450   -8.923549     28975
48973      0.389345   -9.070278     19321
48974      0.383367   -9.193744     49594
48975      0.383220   -9.196774      9997
48976      0.382052   -9.220897     14983
48977      0.378248   -9.299467      9805
48978      0.376134   -9.343131     48128
48979      0.360473   -9.666577     18590
48980      0.353835   -9.803665     43103
48981      0.347877   -9.926715     24536
48982      0.347467   -9.935182     42485
48983      0.343672  -10.013572     46162
48984      0.332580  -10.242641     28530
48985      0.322757  -10.445522      5396
48986      0.312946  -10.648149      6538
48987      0.305946  -10.792727     28048
48988      0.300340  -10.908498     13645
48989      0.299900  -10.917600     19354
48990      0.294255  -11.034184     16474
48991      0.278808  -11.353211     45563
48992      0.276529  -11.400277      8653
48993      0.251184  -11.923725      8690
48994      0.233583  -12.287236     48275
48995      0.172271  -13.553505     24240
48996      0.164884  -13.706085     48523
48997      0.163846  -13.727518     36618
48998      0.102533  -14.993820       772
48999      0.000000  -17.111429     49190

[49000 rows x 3 columns]

In [37]:
df_uncertainty =  pd.DataFrame(list(zip(np_list[2], np_list[4])),columns=['uncertainty','ind'])

In [40]:
df_uncertainty.sort_values('uncertainty',ascending=False,inplace=True)

In [48]:
df_uncertainty

uncertainty    ind
26909     3.541582   1611
8011      3.504629  42369
25807     3.467202  18636
4299      3.450284  30572
20777     3.436961  17520
36334     3.395629   2345
43597     3.390470   5314
227       3.320085  30896
40102     3.319893  11479
29087     3.319103  38787
29866     3.285745  25141
23644     3.279819   7804
14362     3.271077  44783
26164     3.269945  25862
2847      3.242251   8750
32821     3.227726  43793
25290     3.221826  21875
6669      3.213657  23695
27541     3.211326  12357
5492      3.197291  43000
9858      3.195861   3536
2166      3.187250  21422
21119     3.185675  36325
10563     3.184380  43083
13835     3.172538   9649
9082      3.170135  48250
43903     3.165955  43403
13773     3.161723   2747
25580     3.156543   4822
46926     3.143350   6397
...            ...    ...
48733    -8.699195   3153
16058    -8.717897  35878
9106     -8.923549  28975
10419    -9.070278  19321
20072    -9.193744  49594
128      -9.196774   9997
6347     -9.220897  14983
19668    -9.299467   9805
12273    -9.343131  48128
18593    -9.666577  18590
3693     -9.803665  43103
17775    -9.926715  24536
32306    -9.935182  42485
41898   -10.013572  46162
35719   -10.242641  28530
28195   -10.445522   5396
30237   -10.648149   6538
41775   -10.792727  28048
36436   -10.908498  13645
31786   -10.917600  19354
32629   -11.034184  16474
44293   -11.353211  45563
46789   -11.400277   8653
41228   -11.923725   8690
15231   -12.287236  48275
30404   -13.553505  24240
31082   -13.706085  48523
47583   -13.727518  36618
34234   -14.993820    772
45328   -17.111429  49190

[49000 rows x 2 columns]

In [ ]:
# Update the labeled dataset and the unlabeled dataset, respectively
labeled_set += list(torch.tensor(subset)[arg][-ADDENDUM:].numpy())
unlabeled_set = list(torch.tensor(subset)[arg][:-ADDENDUM].numpy()) + unlabeled_set[SUBSET:]

In [24]:
np_list[3]

array([[ 8.122082  ,  0.        ,  0.        , ...,  0.4443373 ,
         0.        ,  0.        ],
       [10.558553  ,  0.        ,  0.932937  , ...,  2.0271432 ,
         0.        ,  0.        ],
       [ 7.874393  ,  0.        ,  0.9578483 , ...,  0.        ,
         0.        ,  0.11378814],
       ...,
       [10.903421  ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [10.573555  ,  0.        ,  0.        , ...,  2.8159897 ,
         0.        ,  0.        ],
       [ 7.0208697 ,  0.        ,  1.6049472 , ...,  2.2811067 ,
         0.        ,  0.128059  ]], dtype=float32)

array([33213, 30693, 19303, ...,  4744, 42846, 41227])

In [15]:
scores = np.max(np_list[0],axis=1)

In [16]:
scores

array([0.61965084, 0.9998971 , 0.8835079 , ..., 0.9984296 , 0.93242294,
       0.9582393 ], dtype=float32)